from summa import summarizer, keywords


#text = """Automatic summarization is the process of reducing a text document with a computer program in order to create a summary that retains the most important points of the original document. As the problem of information overload has grown, and as the quantity of data has increased, so has interest in automatic summarization. Technologies that can make a coherent summary take into account variables such as length, writing style and syntax. An example of the use of summarization technology is search engines such as Google. Document summarization is another."""

#text = """Various demographic, technological and economic changes have been driven by the Web. Behind them is the fundamental desire of people to connect, communi- cate, share and participate [1], motivations that Internet continues to facilitate in ways never before imagined. Undoubtedly, the Web is one of the main techno- logical advances of the 20th century. However, this has not always been the case, it has evolved over time and technological advances: Web 1.0, which consisted of plain text shown in HTML pages, with unorganized data and that did not follow any standard [1]; Web 2.0, a set of social, economic and technological trends, that collectively form the basis of the next generation of the Internet: a more mature and different medium, characterized by user participation, openness and network effects [2]; and, Web 3.0 or also called Semantic Web, a technological evolution of the current Web [3]. The Semantic Web is a rediscovery or fulfill- ment of what the Web pretended to be, a global space of linked data to which meaning is added [4]. The impact of this evolution state of the Web is accelerat- ing as the adoption of the approach grows, and is more integrated into the daily lives of individuals and organizations."""
text = """Sistemas Basados en el Conocimiento es una asignatura que se imparte en décimo ciclo de la titulación de Ingeniería en Sistemas Informáticos y Computación, ofertada por la Universidad Técnica Particular de Loja. La asignatura introduce al profesional en formación en una de las áreas más interesantes, emergentes y prometedoras que ha surgido en nuestra era actual de la sociedad del conocimiento, estructuras de conocimiento abierto y las tecnologías de la Web Semántica. Hoy en día, es imprescindible que nuestros ingenieros, adquieran competencias clave para capturar, modelar, gestionar y explotar datos y conocimiento que en grandes cantidades se generan y están disponibles en la Web y que con diferentes fines pueden ser aprovechados en la práctica laboral, académica y empresarial. En el presente componente académico, se cubren aspectos como: la creación de esquemas de representación de conocimiento y datos, la descripción de recursos y objetos del mundo real mediante esos modelos, la publicación de datos enlazados en la Web, así como su posterior aprovechamiento para efectos de recuperar datos y generar nuevo conocimiento. Cuando un estudiante finalice este componente habrá adquirido la capacidad para identificar áreas y usos potenciales de las tecnologías de la web semántica, modelar dominios de conocimiento e implementar modelos procesables por máquinas."""
#text = """Conocer los conceptos y las tecnologías emergentes de la Web Semántica y la representación de conocimiento,capacidad para construir modelos formales de representación del conocimiento,habilidad para publicar y explotar datos enlazados mediante lenguajes formales"""

print("El resumen: ")
text1 = summarizer.summarize(text, language='spanish' ,words=150)
print (text1)
print("Las palabras clave: ")
print(keywords.keywords(text, language='spanish', words=5))


