INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/PosTag/NOUN", "http://www.w3.org/2000/01/rdf-schema#label", "NOUN");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Sentence/Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/hasToken", "http://data.utpl.edu.ec/vutpl/resource/Token/Token1_Sentence1");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Sentence/Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/dataSentence", "b'Attitude control'");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/PosTag/VERB", "http://www.w3.org/2000/01/rdf-schema#label", "VERB");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token2_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/data", "support");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Sentence/Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/dataSentence", "b'Air traffic control'");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Sentence/Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/dataSentence", "b'Aerospace biophysics'");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token2_Sentence1", "http://www.w3.org/2000/01/rdf-schema#label", "NOUN");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token2_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/lemma", "traffic");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token3_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/lemma", "control");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token1_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/data", "b'Attitude");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token2_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/tokenId", "2");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token1_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/tokenId", "1");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token2_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/data", "traffic");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token3_Sentence1", "http://www.w3.org/2000/01/rdf-schema#label", "NOUN");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token2_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/lemma", "control");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token2_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/data", "engineering");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token1_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/lemma", "b'air");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Sentence/Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/dataSentence", "b'Aerospace engineering'");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Sentence/Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/hasToken", "http://data.utpl.edu.ec/vutpl/resource/Token/Token2_Sentence1");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Sentence/Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/dataSentence", "b'Ground support'");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token2_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/lemma", "biophysic");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token2_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/lemma", "support");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token1_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/data", "b'Air");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token1_Sentence1", "http://www.w3.org/2000/01/rdf-schema#label", "VERB");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token1_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/pos", "http://data.utpl.edu.ec/vutpl/resource/PosTag/NOUN");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token2_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/data", "control");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token2_Sentence1", "http://www.w3.org/2000/01/rdf-schema#label", "ADJ");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token2_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/lemma", "engineering");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token3_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/pos", "http://data.utpl.edu.ec/vutpl/resource/PosTag/NOUN");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token1_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/lemma", "b'aerospace");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token3_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/data", "control");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/PosTag/VERB", "http://www.w3.org/1999/02/22-rdf-syntax-ns#type", "http://data.utpl.edu.ec/vutpl/vocabulary/PosTag");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/PosTag/ADJ", "http://www.w3.org/1999/02/22-rdf-syntax-ns#type", "http://data.utpl.edu.ec/vutpl/vocabulary/PosTag");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Sentence/Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/dataSentence", "b'Aerospace electronics'");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Sentence/Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/dataSentence", "b'Air safety'");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/PosTag/NOUN", "http://www.w3.org/1999/02/22-rdf-syntax-ns#type", "http://data.utpl.edu.ec/vutpl/vocabulary/PosTag");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Sentence/Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/hasToken", "http://data.utpl.edu.ec/vutpl/resource/Token/Token3_Sentence1");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token2_Sentence1", "http://www.w3.org/1999/02/22-rdf-syntax-ns#type", "http://data.utpl.edu.ec/vutpl/vocabulary/Token");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token2_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/pos", "http://data.utpl.edu.ec/vutpl/resource/PosTag/NOUN");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Sentence/Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/sentenceId", "1");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Sentence/Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/dataSentence", "b'Aerospace safety'");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token3_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/tokenId", "3");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token2_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/lemma", "electronic");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token3_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/lemma", "system");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token2_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/data", "electronics");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token2_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/lemma", "safety");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token2_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/data", "safety");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token2_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/pos", "http://data.utpl.edu.ec/vutpl/resource/PosTag/ADJ");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token1_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/pos", "http://data.utpl.edu.ec/vutpl/resource/PosTag/VERB");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token1_Sentence1", "http://www.w3.org/1999/02/22-rdf-syntax-ns#type", "http://data.utpl.edu.ec/vutpl/vocabulary/Token");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Sentence/Sentence1", "http://www.w3.org/1999/02/22-rdf-syntax-ns#type", "http://data.utpl.edu.ec/vutpl/vocabulary/Sentence");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token3_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/data", "systems");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token3_Sentence1", "http://www.w3.org/1999/02/22-rdf-syntax-ns#type", "http://data.utpl.edu.ec/vutpl/vocabulary/Token");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token2_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/data", "electronic");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token1_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/lemma", "b'ground");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token1_Sentence1", "http://www.w3.org/2000/01/rdf-schema#label", "NOUN");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/PosTag/ADJ", "http://www.w3.org/2000/01/rdf-schema#label", "ADJ");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token2_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/data", "biophysics");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token1_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/data", "b'Ground");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Sentence/Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/dataSentence", "b'Aerospace and electronic systems '");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token1_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/data", "b'Aerospace");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Token/Token1_Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/lemma", "b'attitude");
INSERT into tripletas values  ("http://data.utpl.edu.ec/vutpl/resource/Sentence/Sentence1", "http://data.utpl.edu.ec/vutpl/vocabulary/dataSentence", "b'Aerospace control'");
